set -g mouse off
set -g history-limit 5000
setw -g mode-keys vi

# No ESC delay - main cause of dropped keys in browser terminal
set -sg escape-time 0

# No repeat delay
set -g repeat-time 0

# Sync resize with ttyd
setw -g aggressive-resize on

# Statusbar update interval
set -g status-interval 5
